In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_excel("C:/Users/thala/Downloads/Bird Strikes data.xlsx")

In [13]:
df

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,2000-11-23,Caused damage,...,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,30736,1500.0,0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,2001-07-25,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0.0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,2001-09-14,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50.0,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,2002-09-05,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50.0,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,NaN,2003-06-23,No damage,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50.0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25553,321151,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,NaN,2011-12-30,No damage,...,False,DUCK? NO DMG REPTD.,Large,Overcast,Unknown bird - large,N,0,1500.0,0,No
25554,319677,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,NaN,2011-12-30,No damage,...,False,NaN,Small,Some Cloud,Tree swallow,Y,0,0.0,0,No
25555,319680,NaN,NaN,NaN,EC-135,NaN,1,NaN,NaT,No damage,...,False,STRUCK BIRD ON RT FRONT DURING T/O. BIRD REPTD...,NaN,No Cloud,Unknown bird - small,NaN,0,NaN,0,NaN
25556,319679,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,NaN,2011-12-31,No damage,...,False,PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...,Medium,Some Cloud,Unknown bird - medium,Y,0,0.0,0,Yes
25557,319593,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,NaN,2011-12-31,Caused damage,...,False,"HIT CENTER OF RADOME, CAVING IN ABOUT 12"". RAD...",Medium,No Cloud,Red-tailed hawk,N,0,0.0,0,Yes

In [14]:
df['Aircraft: Type'] = df['Aircraft: Type'].fillna('Not Available')
df['Airport: Name'] = df['Airport: Name'].fillna('Not Available')
df['Altitude bin'] = df['Altitude bin'].fillna('Not Available')
df['Aircraft: Make/Model'] = df['Aircraft: Make/Model'].fillna('Not Available')
df['Wildlife: Number struck'] = df['Wildlife: Number struck'].fillna('Not Available')
df['Effect: Impact to flight'] = df['Effect: Impact to flight'].fillna('Not Available')
df['When: Phase of flight']=df['When: Phase of flight'].fillna('Not Available')
df_cleaned = df.fillna('Unvailable')
display(df_cleaned.head(10))
df_cleaned.info()

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,2000-11-23 00:00:00,Caused damage,...,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,30736,1500.0,0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,Not Available,2001-07-25 00:00:00,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0.0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,Not Available,2001-09-14 00:00:00,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50.0,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,2002-09-05 00:00:00,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50.0,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,Not Available,2003-06-23 00:00:00,No damage,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50.0,0,No
5,218432,Airplane,GUAYAQUIL/S BOLIVAR,< 1000 ft,A-300,Over 100,537,Not Available,2003-07-24 00:00:00,No damage,...,False,NO DMG. BIRD REMAINS ON F/O WINDSCREEN.,Small,No Cloud,Unknown bird - small,N,0,0.0,0,No
6,221697,Airplane,NEW CASTLE COUNTY,< 1000 ft,LEARJET-25,Over 100,227,Other,2003-08-17 00:00:00,Caused damage,...,True,Unvailable,Small,No Cloud,European starling,N,1481711,150.0,0,No
7,236635,Airplane,WASHINGTON DULLES INTL ARPT,< 1000 ft,A-320,Over 100,320,Other,2006-03-01 00:00:00,Caused damage,...,False,WS ASSISTED IN CLEAN-UP OF 273 STARLINGS AND 1...,Small,Some Cloud,European starling,Y,1483141,100.0,0,No
8,207369,Airplane,ATLANTA INTL,< 1000 ft,DC-9-30,2 to 10,9,Aborted Take-off,2000-01-06 00:00:00,No damage,...,False,Unvailable,Small,Some Cloud,Rock pigeon,N,0,0.0,0,No
9,204371,Airplane,ORLANDO SANFORD INTL AIRPORT,< 1000 ft,A-330,2 to 10,4,Not Available,2000-01-07 00:00:00,No damage,...,False,FLT 057,Small,Some Cloud,Unknown bird - small,N,0,0.0,0,No

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25558 entries, 0 to 25557
Data columns (total 26 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Record ID                                25558 non-null  int64
 1   Aircraft: Type                           25558 non-null  object
 2   Airport: Name                            25558 non-null  object
 3   Altitude bin                             25558 non-null  object
 4   Aircraft: Make/Model                     25558 non-null  object
 5   Wildlife: Number struck                  25558 non-null  object
 6   Wildlife: Number Struck Actual           25558 non-null  int64
 7   Effect: Impact to flight                 25558 non-null  object
 8   FlightDate                               25558 non-null  object
 9   Effect: Indicated Damage                 25558 non-null  object
 10  Aircraft: Number of engines?             25558 non-null  object
 11  Aircraft: Airline/Operator               25558 non-null  object
 12  Origin State                             25558 non-null  object
 13  When: Phase of flight                    25558 non-null  object
 14  Conditions: Precipitation                25558 non-null  object
 15  Remains of wildlife collected?           25558 non-null  bool
 16  Remains of wildlife sent to Smithsonian  25558 non-null  bool
 17  Remarks                                  25558 non-null  object
 18  Wildlife: Size                           25558 non-null  object
 19  Conditions: Sky                          25558 non-null  object
 20  Wildlife: Species                        25558 non-null  object
 21  Pilot warned of birds or wildlife?       25558 non-null  object
 22  Cost: Total $                            25558 non-null  int64
 23  Feet above ground                        25558 non-null  object
 24  Number of people injured                 25558 non-null  int64
 25  Is Aircraft Large?                       25558 non-null  object
dtypes: bool(2), int64(4), object(20)
memory usage: 4.7+ MB

In [15]:
df_cleaned.describe()

,Record ID,Wildlife: Number Struck Actual,Cost: Total $,Number of people injured
count,25558.000000,25558.000000,2.555800e+04,25558.000000
mean,253916.085609,2.691525,5.567354e+03,0.001056
std,38510.453382,12.793975,1.219713e+05,0.050420
min,1195.000000,1.000000,0.000000e+00,0.000000
25%,225783.750000,1.000000,0.000000e+00,0.000000
50%,248749.000000,1.000000,0.000000e+00,0.000000
75%,269168.750000,1.000000,0.000000e+00,0.000000
max,321909.000000,942.000000,1.239775e+07,6.000000

In [16]:
display(df_cleaned.head(10))

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,2000-11-23 00:00:00,Caused damage,...,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,30736,1500.0,0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,Not Available,2001-07-25 00:00:00,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0.0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,Not Available,2001-09-14 00:00:00,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50.0,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,2002-09-05 00:00:00,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50.0,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,Not Available,2003-06-23 00:00:00,No damage,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50.0,0,No
5,218432,Airplane,GUAYAQUIL/S BOLIVAR,< 1000 ft,A-300,Over 100,537,Not Available,2003-07-24 00:00:00,No damage,...,False,NO DMG. BIRD REMAINS ON F/O WINDSCREEN.,Small,No Cloud,Unknown bird - small,N,0,0.0,0,No
6,221697,Airplane,NEW CASTLE COUNTY,< 1000 ft,LEARJET-25,Over 100,227,Other,2003-08-17 00:00:00,Caused damage,...,True,Unvailable,Small,No Cloud,European starling,N,1481711,150.0,0,No
7,236635,Airplane,WASHINGTON DULLES INTL ARPT,< 1000 ft,A-320,Over 100,320,Other,2006-03-01 00:00:00,Caused damage,...,False,WS ASSISTED IN CLEAN-UP OF 273 STARLINGS AND 1...,Small,Some Cloud,European starling,Y,1483141,100.0,0,No
8,207369,Airplane,ATLANTA INTL,< 1000 ft,DC-9-30,2 to 10,9,Aborted Take-off,2000-01-06 00:00:00,No damage,...,False,Unvailable,Small,Some Cloud,Rock pigeon,N,0,0.0,0,No
9,204371,Airplane,ORLANDO SANFORD INTL AIRPORT,< 1000 ft,A-330,2 to 10,4,Not Available,2000-01-07 00:00:00,No damage,...,False,FLT 057,Small,Some Cloud,Unknown bird - small,N,0,0.0,0,No

In [17]:
df_cleaned.isnull().sum()

Record ID                                  0
Aircraft: Type                             0
Airport: Name                              0
Altitude bin                               0
Aircraft: Make/Model                       0
Wildlife: Number struck                    0
Wildlife: Number Struck Actual             0
Effect: Impact to flight                   0
FlightDate                                 0
Effect: Indicated Damage                   0
Aircraft: Number of engines?               0
Aircraft: Airline/Operator                 0
Origin State                               0
When: Phase of flight                      0
Conditions: Precipitation                  0
Remains of wildlife collected?             0
Remains of wildlife sent to Smithsonian    0
Remarks                                    0
Wildlife: Size                             0
Conditions: Sky                            0
Wildlife: Species                          0
Pilot warned of birds or wildlife?         0
Cost: Total $                              0
Feet above ground                          0
Number of people injured                   0
Is Aircraft Large?                         0
dtype: int64

In [18]:
 df.to_excel("C:/Users/thala/Downloads/BS3_Cleaned.xlsx",index= False)